/**
 * TypeScript declarations for docs app
 */

// Virtual modules generated by @sigx/ssg at build time.
// The package's "./virtual" types entry is missing from the published tarball
// (points at src/client.d.ts which is not shipped), so we declare them locally.
declare module 'virtual:ssg-navigation' {
    import type { NavigationConfig, NavSection } from '@sigx/ssg';

    export const navigation: Record<string, NavigationConfig>;
    export const collections: string[];
    export function getCollectionNav(name: string): NavigationConfig | undefined;
    export function detectCollection(path: string): string | undefined;
    export function getSidebar(name: string): NavSection[];

    const _default: {
        navigation: typeof navigation;
        collections: typeof collections;
        getCollectionNav: typeof getCollectionNav;
        detectCollection: typeof detectCollection;
        getSidebar: typeof getSidebar;
    };
    export default _default;
}

declare module 'virtual:ssg-routes' {
    const routes: unknown[];
    export default routes;
}

declare module 'virtual:generated-layouts' {
    export const setupLayouts: <T>(routes: T) => T;
    export const LayoutRouter: unknown;
}

// MDX content modules — @mdx-js/rollup compiles these to component modules at build time.
declare module '*.mdx' {
    const MDXComponent: (props: Record<string, unknown>) => unknown;
    export default MDXComponent;
    export const frontmatter: Record<string, unknown>;
}
